name: Build and Deploy to EC3 

on:
  push:
    branches:
      - main

jobs:
  build_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/email-writer-sb:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/email-writer-sb:latest

  deploy:
    needs: build_job
    runs-on: [aws-ec3]

    steps:
      - name: Install Docker if not present
        run: |
          if ! command -v docker &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
          fi

      - name: Pull Image from DockerHub
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/email-writer-sb:latest

      - name: Delete old container
        run: sudo docker rm -f email-writer-sb-container || true

      - name: Run Docker Container
        run: |
          sudo docker run -d -p 8080:8080 \
            -e GEMINI_URL=${{ secrets.GEMINI_URL }} \
            -e GEMINI_KEY=${{ secrets.GEMINI_KEY }} \
            --name email-writer-sb-container \
            ${{ secrets.DOCKER_USERNAME }}/email-writer-sb:latest
